#!/bin/sh
# Generate a profanity seed keypair on this machine.
#
# profanity mode never sees a private key: the miner is handed the public half
# and reports an offset. That property starts here, so the pair has to be made
# somewhere you trust. This writes nothing to disk and sends nothing anywhere.
#
# Both halves are read out of two independent openssl renderings of the same
# key, and the script fails if they disagree. That is not paranoia about openssl:
# the DER-and-sed one-liner this replaces predates the `EC-Parameters` line
# openssl 3 prints ahead of the DER, so its label never appears and its first
# line is 128 hex characters of header, wrapper and private key run together --
# exactly the length of the public key it is supposed to be. Nothing downstream
# notices either: a wrong seed still produces a well-formed final key, for an
# address nobody can spend from.
#
# Usage:
#   . scripts/profanity-keygen.sh           set the variables in this shell
#   eval "$(scripts/profanity-keygen.sh)"   the same, without sourcing
#   scripts/profanity-keygen.sh             print the pair and the export lines
#
# Sets PROFANITY_PK, the 64-hex seed private key to keep, and PROFANITY_PUBKEY,
# the 128-hex public key for `1miner profanity --public-key`.

# Whether this file is sourced decides everything below, so it is settled first.
# `set -e` in a sourced file applies to the shell that sourced it, which in an
# interactive shell means the next failed command closes the terminal.
_pk_sourced=0
if [ -n "${ZSH_VERSION-}" ]; then
    case ${ZSH_EVAL_CONTEXT-} in *:file*) _pk_sourced=1 ;; esac
elif [ -n "${BASH_VERSION-}" ]; then
    [ "${BASH_SOURCE-$0}" = "$0" ] || _pk_sourced=1
fi
[ "$_pk_sourced" -eq 1 ] || set -eu

_pk_generate() {
    for _pk_tool in openssl od sed tr; do
        if ! command -v "$_pk_tool" >/dev/null 2>&1; then
            printf 'profanity-keygen: %s is not installed\n' "$_pk_tool" >&2
            return 1
        fi
    done

    _pk_pem=$(openssl ecparam -genkey -name secp256k1 -noout 2>/dev/null)
    case $_pk_pem in
        *"BEGIN EC PRIVATE KEY"*) ;;
        *)
            printf 'profanity-keygen: openssl did not produce a secp256k1 key\n' >&2
            return 1
            ;;
    esac

    # First reading: the DER, where each half is pinned in place by the bytes
    # around it, so a match means the structure was the one expected.
    _pk_der=$(printf '%s\n' "$_pk_pem" | openssl ec -outform DER 2>/dev/null |
        od -An -v -tx1 | tr -d ' \n')
    _pk_priv=$(printf '%s' "$_pk_der" | sed -n \
        's/^30740201010420\([0-9a-f]\{64\}\)a00706052b8104000aa14403420004[0-9a-f]\{128\}$/\1/p')
    _pk_pub=$(printf '%s' "$_pk_der" | sed -n \
        's/^30740201010420[0-9a-f]\{64\}a00706052b8104000aa14403420004\([0-9a-f]\{128\}\)$/\1/p')

    # Second reading: openssl's own text rendering of that same key, which puts
    # the halves under labels rather than at offsets.
    _pk_text=$(printf '%s\n' "$_pk_pem" | openssl ec -text -noout 2>/dev/null)
    _pk_priv2=$(printf '%s\n' "$_pk_text" |
        sed -n '/^priv:/,/^pub:/p' | sed '1d;$d' | tr -cd '0-9a-f')
    _pk_pub2=$(printf '%s\n' "$_pk_text" |
        sed -n '/^pub:/,/^ASN1 OID:/p' | sed '1d;$d' | tr -cd '0-9a-f')

    if [ ${#_pk_priv} -ne 64 ] || [ ${#_pk_pub} -ne 128 ]; then
        printf 'profanity-keygen: cannot find the keypair in the DER openssl produced\n' >&2
        return 1
    fi
    if [ "$_pk_priv" != "$_pk_priv2" ] || [ "04$_pk_pub" != "$_pk_pub2" ]; then
        printf 'profanity-keygen: the two readings disagree, so one is wrong; use neither\n' >&2
        return 1
    fi

    PROFANITY_PK=$_pk_priv
    PROFANITY_PUBKEY=$_pk_pub
    export PROFANITY_PK PROFANITY_PUBKEY
}

_pk_report() {
    # The report goes to stderr so that stdout carries nothing but the export
    # lines, which is what makes `eval "$(...)"` work.
    cat >&2 <<REPORT

Seed keypair generated by openssl on this machine. Nothing was written to disk.

  private key  $PROFANITY_PK
  public key   $PROFANITY_PUBKEY

Copy the private key somewhere safe before this shell goes away. It is the half
that will control the mined address, and the half nothing else ever needs: mine
with the public one, here or on hardware belonging to somebody else.

  1miner profanity --public-key "\$PROFANITY_PUBKEY" --leading 0
  scripts/profanity-final-key.sh --offset 0x<the offset the miner printed>

REPORT

    if [ "$_pk_sourced" -eq 1 ]; then
        printf 'PROFANITY_PK and PROFANITY_PUBKEY are set in this shell.\n\n' >&2
        return 0
    fi

    printf 'export PROFANITY_PK=%s\n' "$PROFANITY_PK"
    printf 'export PROFANITY_PUBKEY=%s\n' "$PROFANITY_PUBKEY"
    # A terminal on stdout means nobody is capturing those lines, so say how to.
    if [ -t 1 ]; then
        printf 'To set them in this shell instead of reading them:\n' >&2
        printf '  eval "$(scripts/profanity-keygen.sh)"\n\n' >&2
    fi
}

# Sourcing leaves the shell as it was found, apart from the two exports. The
# status of this call is the status of the file, so no exit or return follows:
# an `exit` here would close the terminal of anyone who sourced it.
_pk_finish() {
    unset -f _pk_generate _pk_report _pk_finish
    unset _pk_sourced _pk_tool _pk_pem _pk_der _pk_text \
        _pk_priv _pk_pub _pk_priv2 _pk_pub2
    return "$1"
}

if _pk_generate; then
    _pk_report
    _pk_finish 0
else
    _pk_finish 1
fi
